version: "3"

services:
  web:
    build: ./docker/web
    depends_on:
      - meili
      - app
    ports:
      - "3000:80"

  meili:
    image: getmeili/meilisearch
    ports:
      - "7700:7700"
    volumes:
      - ./data/meili:/meili_data

  app:
    build: .
    command: yarn dev
    volumes:
      - "./pages:/app/pages"
      - "./styles:/app/styles"
      - "./public:/app/public"
      - "./scripts:/app/scripts"
    depends_on:
      - meili
