version: "3"

services:
  web:
    build: ./docker/web
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=learn-id.holodata.org
      - LETSENCRYPT_HOST=learn-id.holodata.org
    networks:
      - default
      - webproxy
    depends_on:
      - meili
      - app

  meili:
    image: getmeili/meilisearch
    ports:
      - "7700:7700"
    volumes:
      - ./data/meili:/meili_data

  app:
    build: .
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - "./pages:/app/pages"
      - "./styles:/app/styles"
      - "./public:/app/public"
      - "./scripts:/app/scripts"
    depends_on:
      - meili
